### ISSUE TITLE
[BUG] ffmpeg apng weird decoding

### ISSUE THREAD

**Issue by EngineMachiner** [TeamRizu/OutFox#176]
**Give an example of what is wrong**
Original apng
https://i.imgur.com/OiPWxiy.png

_Type here what is wrong or/with pictures._
It does something weird...
https://i.imgur.com/oRUbNlm.mp4
https://i.imgur.com/SieqcuI.png

**Given an example of what it should look like**
It should look like the original file.

**Comment by Scraticus** [comment]
can you confirm this is still an issue?

**Comment by EngineMachiner** [comment]
It can't load .apng files now. So I can't really tell. It does read them as .png with one single state.
Using 4.12.0.

**Comment by Scraticus** [comment]
apng is fixed once more, ensure your files are correctly .apng files for the game to process them properly.

**Comment by EngineMachiner** [comment]
Just tested in one of the recent test builds for windows, and it's still not possible to load .apng files. There are no errors, though.
