### ISSUE TITLE
[BUG] Not launching at all on twister os due to ARCH conflict on cmake

### ISSUE THREAD

**Issue by snil4** [TeamRizu/OutFox#216]
**Describe how it crashed by giving us those informations:**

I'm trying to run the game on my raspberry pi 400 running twister os, it worked just fine on pi os but twister os seems to crash every time on lauch even on a clean install with or without portable.ini.

[info.txt](https://github.com/TeamRizu/OutFox/files/6029875/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6029876/log.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6029899/crashinfo.txt)

**Explain how we can reproduce the error**

1. Start the game
2. wait for the songs to load
3. Game crashed

**Additional information**

I tried running it with gdb and it says something about libarmmem.so although I have no idea if that has any relation to the problem or not.

**Comment by Scraticus** [comment]
should be fixed in 4.9.7GG

**Comment by snil4** [comment]
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6034246/crashinfo.txt)
still happening, same error on 4.9.7gg

**Comment by Scraticus** [comment]
did you remove the preference.ini for 4.9.7?

**Comment by snil4** [comment]
It's a clean install, I even reflashed twister os with only the vulkan mesa drivers installed. adding the files again after more tries and added a gdb log
[info.txt](https://github.com/TeamRizu/OutFox/files/6036525/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6036526/log.txt)
[gdb.txt](https://github.com/TeamRizu/OutFox/files/6036528/gdb.txt)
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6036530/crashinfo.txt)

**Comment by Scraticus** [comment]
you need to run ``bt`` in gdb after the crash to generate a backtrace for us, can you do that?

many thanks

**Comment by snil4** [comment]
#0  0xb6fbc1dc in strlen () at /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00208212 in  ()
Not sure if this is what you wanted but these are the lines in prints when running `bt` after the crash

**Comment by Scraticus** [comment]
I'm testing a fix for this, hopefully the next alpha will have the solution.

**Comment by Scraticus** [comment]
Should be fixed in 4.9.9, was a debug check for ARMv7 (to ensure it wasn't doing anything 64bit) and it was crashing the game on 32bit OS's confirm when we release, but it should be solved.

**Comment by akureyrakirkja** [comment]
Getting this same issue, still crashed on 4.9.9 when it was available

**Comment by Scraticus** [comment]
Re-opening this as we need to rebuild the game as a different ARM 32bit binary. 

Our ARMv7 builds _should_ be working, but I will install the game on my pi400 with twister and see what's going on.

**Comment by Scraticus** [comment]
Could you let me know where your installation is please?

I think this is a potential permissions issue, and I need to know where you installed it to so I can troubleshoot further. 

Let me know when you're back so I can work with you.

Latest twisterOS extracted to desktop works fine with 4.9.9HF3b, but I won't close this yet until we have solved your issue

**Comment by Scraticus** [comment]
Fixed in 4.10.0

**Comment by Scraticus** [comment]
This is properly fixed in the next alpha.

The issue was the library called by Twister OS.

Sorry I wasn't able to spot this earlier.

![image](https://user-images.githubusercontent.com/11047768/152904541-e1fc1ce9-e79c-4480-b6e4-36d0dd83c8b4.png)
