### ISSUE TITLE
Game Crash in Extended/Course Mode [Dance] when entering options

### ISSUE THREAD

**Issue by Jubo88** [TeamRizu/OutFox#29]
When entering to Extra Options Menu when selecting a song/course in Extended/Courses Mode. 
After scrolling through the bottom to go to the next screen for any of the options of 

Gameplay / Main Option / Additional Options / Effects / Return Music Selection Menu.

Just crashed... But pressing ESC key doesn't... haha~!

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/4918921/crashinfo.txt)

[log.txt](https://github.com/TeamRizu/OutFox/files/4918922/log.txt)

**Comment by JoseVarelaP** [comment]
This was reported beforehand during a Twitch stream. I have identified the bug and it has been fixed. It has been due to the previous process to store the next screen's information. It'll be for Alpha 5 or sooner.

**Comment by Scraticus** [comment]
Just re-opening this to confirm we've fixed it. Jubo will add the new crashlogs that point to a checkpoint_m chain.

Thanks bro

**Comment by Jubo88** [comment]
Update on the crash appearing again on 4.8.1 build

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5078657/crashinfo.txt)

[log.txt](https://github.com/TeamRizu/OutFox/files/5078659/log.txt)

requested from Scraticus :)

**Comment by Scraticus** [comment]
We fixed some of the sound files masking this issue, which was in the 4.8.2 hotfix, so it's easily reproducible now.

**Comment by JoseVarelaP** [comment]
Since there hasn't been any new reports of this bug happening, it can be safe to assume that it has been fixed, so i'm closing this now.

**Comment by JoseVarelaP** [comment]
Right, reopening this after Jubo has pointed out it still crashes. Is it actually just a Windows only bug?!

**Comment by Jubo88** [comment]
Just an update on the new version 4.96HF. Still crashes. I didn't bother to report more since Squirrel (on Discord) point out to me it will be dealt with more thoroughly on this rabbit hole in Alpha 5. But here are the logs/crash. 
It been sometime since the last time. I bet there are some things missing in between the lines like .zip packages or the additional folders prefs things...

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/5740043/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5740046/log.txt)

**Comment by Scraticus** [comment]
Fixed in 4.9.7, songs are correctly generated now due to the new random system 

See #22

**Comment by Jubo88** [comment]
I still have the crash, I tinker and further investigate it more. It all narrows it down to the my profile (transfer from very old profile from sm3.9 I assume?), stats.xml is causing it. 
My copy of my profile below, I deleted catalog,xml and slotted as 5/6th slot prevent overwrite mains.
[00000005.zip](https://github.com/TeamRizu/OutFox/files/6011206/00000005.zip)

Crashlogs + logs if it matters cause it does not show it at all.
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6011242/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6011247/log.txt) 

I guessing this won't be looked at cause profiles sm3.9 or any version for that matter to sm5.* will not be recommended. but just a future reference if some does in the future. And its unique and odd issue.

**Comment by Scraticus** [comment]
can we have an update on this one?

Cheers

**Comment by Jubo88** [comment]
Jose found the problem. it was A-Mod problem. https://discord.com/channels/422897054386225173/739814347567530024/812373022341333092 

> Since courses don't give Song data (directly)
> Amod conversion cannot happen

Jose fixed it. If scroll a bit down in that link message in discord.

I tested on 4.97... But after that session on testing... yesterday. 
Today I open up the game it crashes on load now. Stops at loading profiles after song scan.

[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/6023154/crashinfo.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6023155/log.txt)

**Comment by Scraticus** [comment]
so is this fix in a release or to be released?

**Comment by Jubo88** [comment]
> so is this fix in a release or to be released?

Fixed on release.

**Comment by Jubo88** [comment]
> so is this fix in a release or to be released?

NVM on the fixed on release of 4.97, it is now fixed when it is going to be released. Fixed by Jose.

I still getting crashes on A-Mod set on courses on 4.97. Previously it was going non-crashing due to not setting A-Mod, it was Set as C-Mod or M-Mod. My mistake.

**Comment by Jubo88** [comment]
Comfirmed Fixed on 4.97GG for me. Thanks!
