### ISSUE TITLE
[Game Crash] Faulty simfile (?)

### ISSUE THREAD

**Issue by Kaede573** [TeamRizu/OutFox#378]
OutFox-5.3.0-alpha-4.9.9-amd64-date-20210731

It looks like the song loader (StepMania startup) is tripping on a specific simfile in my library, which makes it crash.
I have attached the file as well as logs.

ps. I have loaded my entire library (41k songs) successfully after isolating that file (moving it away), hopefully this is the only file causing a crash. Also, I had to rename the sm file to sm.txt here otherwise Github rejects the file.

[PAPAYAPA BASS.sm.txt](https://github.com/TeamRizu/OutFox/files/6912360/PAPAYAPA.BASS.sm.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/6912362/userlog.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/6912361/log.txt)

**Comment by aryoadhi** [comment]
This might be related to issue #393 ?

**Comment by Scraticus** [comment]
This bug has been fixed in the new HF4 due out shortly. Thanks for reporting it!

**Comment by Kaede573** [comment]
Hello, thanks for the feedback and fix, unfortunately it looks like the crash is still happening using latest alpha (Alpha 4.9.10 / Aug 27th).
I have attached userlog and log (for both Windows and Linux amd64 builds).

[ubuntu_log.txt](https://github.com/TeamRizu/OutFox/files/7111600/ubuntu_log.txt)
[ubuntu_userlog.txt](https://github.com/TeamRizu/OutFox/files/7111601/ubuntu_userlog.txt)
[win_log.txt](https://github.com/TeamRizu/OutFox/files/7111602/win_log.txt)
[win_userlog.txt](https://github.com/TeamRizu/OutFox/files/7111603/win_userlog.txt)

**Comment by Scraticus** [comment]
in the discord server, dm me the simfile so i can see where it's crashing. it looks like a _really_ bad audio file from the logs.

lets squash this one

**Comment by Kaede573** [comment]
Late comment, but I can confirm this is still crashing on 4.10.0 (as well as on the most recent closed builds).
5.1 beta 2 doesn't crash, however it _does_ fail to playback (there is no music).

Foobar2000 reports no issue decoding the entire file (converting to WAV).
ogginfo doesn't report anything special either
> Processing file "PAPAYAPA BASS.ogg"...
> 
> New logical stream (#1, serial: 00004bb6): type vorbis
> Vorbis headers parsed for stream 1, information follows...
> Version: 0
> Vendor: Xiph.Org libVorbis I 20070622 (1.2.0)
> Channels: 2
> Rate: 48000
> 
> Nominal bitrate: 160,000000 kb/s
> Upper bitrate not set
> Lower bitrate not set
> User comments section follows...
> 	Encoded by=iTunes 12.3.2.35
> 	ALBUM=beatmania IIDX 24 SINOBUZ ORIGINAL SOUNDTRACK
> 	TITLE=PAPAYAPA BASS
> 	Part of a set=2/2
> 	TRACKNUMBER=4/18
> 	COMMENTS=4
> 	ARTIST=かめりあ feat. ななひら
> 	DATE=2017
> 	Band=KONAMI
> 	GENRE=Soundtrack
> Vorbis stream 1:
> 	Total data length: 2574491 bytes
> 	Playback length: 2m:06.048s
> 	Average bitrate: 163,397499 kb/s
> Logical stream 1 ended

**Comment by Scraticus** [comment]
Right, downloaded it, it is indeed a faulty simfile.

#MUSIC points to an image file, not an audio one. so the file handler throws a wobbly and it freezes.

![image](https://user-images.githubusercontent.com/11047768/144424834-3a374609-67b2-435b-9026-deaca57dc8f8.png)

We'll add a fix to this for the next alpha to 'ignore' bad #MUSIC entries and see if there is a music file in the folder or not.

Thanks for reporting it.
