### ISSUE TITLE
[BUG] Saving simfile from editor makes steps disappear

### ISSUE THREAD

**Issue by SupraGL** [TeamRizu/OutFox#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 11 Family

### CPU

AMD Ryzen 7 5800H with Radeon Graphics

### GPU

NVIDIA GeForce RTX 3060

### Storage

1TB

### Game Version

4.15.0

### Game Mode

dance

### Theme

Real game version is 4.16.0, but also seen in 4.15.0
Seen with Soundwave (Alpha 0.4.15) and XX -STARLiGHT- twopointzero (last merge)

### Describe the problem

When I edit a simfile with charts from Single Beginner to Expert or Single Beginner to Challenge, all the charts are correctly visible when I switch between them using F5 and F6. However, when I save, only the chart I was on is visible, and the other charts have their steps disappear.

Also, when I try to refresh from disk, before or after, sometimes it solves the issue, sometimes it crashes.

### Describe what should happen

When I save, all the steps from all charts should still be visible, and I would not have to refresh from disk everytime I save to get the steps back. Also, refresh from disk should not crash.

### Relevant Log output

**BEFORE SAVING**
CHALLENGE
<img width="962" alt="image" src="https://user-images.githubusercontent.com/33940430/182007244-2dfe393a-b41a-4dd8-9a4a-289f0aebfc06.png">
EXPERT
<img width="962" alt="image" src="https://user-images.githubusercontent.com/33940430/182007255-e509b6b7-8988-4a7a-8ffb-0ce31274869f.png">
**AFTER SAVING**
CHALLENGE
<img width="962" alt="image" src="https://user-images.githubusercontent.com/33940430/182007291-9233f8cc-f7f1-4ae2-9e0f-1147e19ee68f.png">
EXPERT
<img width="962" alt="image" src="https://user-images.githubusercontent.com/33940430/182007308-aaa8d70c-b206-42dd-9558-70045a50ea0f.png">
**LOG IF NEEDED**
[log.txt](https://github.com/TeamRizu/OutFox/files/9227949/log.txt)

**CRASH INFO AFTER REFRESH**
[crashinfo.txt](https://github.com/TeamRizu/OutFox/files/9227971/crashinfo.txt)

**Comment by SHRMP0** [comment]
This is an upstream bug that was already fixed on Alpha V builds but not yet on Alpha 4. You can find an explanation on why it happens and how to recover your steps below, as explained by @JoseVarelaP on Discord:
 
> "No, your steps are not gone. The editor has not a good idea of what charts were created and not saved, so it attempts to erase those from memory so they don’t show up in gameplay.
> But there’s no like accurate way as it was written, so there’s a chance it will wipe the entire chart list from memory on that song. 
> Again, from memory, not disk. To mitigate it for now, just Reload Songs/Courses when you’re done editing."

**Comment by AngledLuffa** [comment]
This is definitely a new bug as far as I can tell.  I haven't seen it before when editing.

Is there a fix planned for Alpha 4, or is Alpha 5 going to be released soon?

**Comment by SupraGL** [comment]
Bumping this issue as I still get crashes when I try to refresh from disk like mentioned above. I updated to 4.18.1 and it still happens at times.
[ProjectOutfox.Crash.2022-11-15--17.01.32.log](https://github.com/TeamRizu/OutFox/files/10016868/ProjectOutfox.Crash.2022-11-15--17.01.32.log)
[ProjectOutfox.MainLog.2022-11-15--17.01.32.log](https://github.com/TeamRizu/OutFox/files/10016870/ProjectOutfox.MainLog.2022-11-15--17.01.32.log)

**Comment by bonimy** [comment]
Will a fix for this ever get pushed to alpha 4 lts?

**Comment by Scraticus** [comment]
This is fixed on latest alpha pre-test.

We will look at a backport, @JoseVarelaP will let you know if it is possible
