### ISSUE TITLE
[BUG] Dancepad doesn't detected

### ISSUE THREAD

**Issue by bademux** [TeamRizu/OutFox#689]
### Please Select the game mode your feature request is about.

dance

### Is your feature request related to a problem?

Dancepad doesn't detected `2563:0506 ShenZhen ShanWan Technology Co., Ltd. USB DancePad`  
 <img src="https://github.com/TeamRizu/OutFox/assets/1610049/c221fd17-46e4-45b4-b339-cfe02689c1cd" width="150" />

Dancepad runs well on Stepmania 5.1.0-b2 (flatpack)

### Describe the solution you'd like

Dancepad detected and working

### Additional context

Tested on latest 20230430 app version 
Device: SteamDeck.

**Comment by bademux** [comment]
upd: HIDAPI (as per https://outfox.wiki/user-guide/setup/getting-started/) doesn't change anything

**Comment by Scraticus** [comment]
you need to use best guess - so inputsetdinput=1 and inputsetxinput=1

you may also have to set linuxusejsendpoint=0 as well.

I am changing how this works in 042, as i've written a brand new deck driver which fixes the Steam input overlay issues for good.

Thanks for reporting this, will mark it as fixed, but leave it open until we release 042 - there will be a test push to the steamdeck branch on steam to test this in a few days, so i'll ping you here for it

**Comment by Scraticus** [comment]
Fixed in 042, you can use SDL2, and the steamdeck driver in this new build

**Comment by bademux** [comment]
> Fixed in 042, you can use SDL2, and the steamdeck driver in this new build

@Scraticus but is not related to steamdeck driver, it is about Dancepade. Dancepade still doesn't work.
Please reopen.

**Comment by Scraticus** [comment]
this is now fixed, i'll push up a specific build for the deck to resolve this issue for you guys in 043
